services:
    minio:
      image: 'bitnami/minio:latest'
      ports:
        - '9000:9000'
        - '9001:9001'
      environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 15s
        timeout: 10s
        retries: 3
      tmpfs:
        - /bitnami/minio/data:rw,size=${STORAGE_SIZE}

    minio-client:
        image: 'bitnami/minio-client'
        environment:
        - MINIO_HOST=minio
        - MINIO_PORT=9000
        - ALIAS=${ALIAS}
        - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
        - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
        - USER=${USER}
        - PASSWORD=${PASSWORD}
        - BUCKET=${BUCKET}
        - QUOTA=${QUOTA}
        command: sh /mc_client/mc_runc.sh      
        depends_on:
          minio:
            condition: service_healthy
        volumes:
        - ./mc_client:/mc_client
    app:
      build:
            context: ./client
            dockerfile: Dockerfile
      environment:
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${USER}
      - MINIO_SECRET_KEY=${PASSWORD}
      - STORAGE_SIZE=${STORAGE_SIZE}
      - QUOTA=${QUOTA}
      depends_on:
        minio:
          condition: service_healthy
        minio-client:
          condition: service_completed_successfully
      volumes:
        - ./client:/app/
      command: python /app/client.py
      